version: '2'
services:
  guitar:
    container_name: guitar
    image: matejkubinec/chordpro
    working_dir: /wd
    volumes:
      - .:/wd
    command:
      - --filelist=list.txt
      - --config=./config/guitar.json
      - --output=books/guitar.pdf

  ukulele:
    container_name: ukulele
    image: matejkubinec/chordpro
    working_dir: /wd
    volumes:
      - .:/wd
    command:
      - --filelist=list.txt
      - --config=./config/ukulele.json
      - --output=books/ukulele.pdf
